controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mecanumbot_drive_controller:
      type: mecanumbot_controller/MecanumbotDriveController

mecanumbot_drive_controller:
  ros__parameters:
    fl_wheel_joint_name: drivewh2_l
    fr_wheel_joint_name: drivewh2_r
    rl_wheel_joint_name: drivewh1_l
    rr_wheel_joint_name: drivewheel1_r
    wheel_radius: 0.03
    wheel_distance:
      width: 0.46
      length: 0.40
